[package]
name = "new_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
rand = "0.8.5"
num = "0.4.0"
merging-iterator = "1.3.0"
par-map = "0.1.4"
rdxsort = "0.3.0"